[package]
name = "cloudkv"
version = "0.0.1"
edition = 2023
authors = []

[dependencies]
boost = { version = "1.81.0", components = ["headers", "system", "thread", "serialization"] }
fmt = "9.1.0"
range-v3 = "0.12.0"
ms-gsl = "4.0.0"
spdlog = "1.11.0"
folly = "2022.01.31.00"