add_rules("mode.debug", "mode.release")

set_warnings("all", "error")
set_languages("c++17")

package("scope_guard")
	add_urls("https://github.com/Neargye/scope_guard.git")
	add_versions("0.9.1", "8444f7096ea4874817d3421dc8ca596e984d6eaf")
	add_deps("cmake")
	on_install(function(package)
        import("package.tools.cmake").install(package)
    end)
package_end()

add_requires("boost 1.76.0", { configs = { thread = true, serialization = true } })
add_requires("fmt 8.0.1")
add_requires("spdlog v1.9.1", { config = { fmt_external = true } })
add_requires("abseil 20210324.2")
add_requires("conan::range-v3/0.11.0", { alias = "range-v3" })
add_requires("scope_guard 0.9.1")

target("cloudkv")
    set_kind("$(kind)")
    add_includedirs("include", { public = true })
    add_includedirs("src/", { public = false })
    add_files("src/**.cpp")
    add_defines("BOOST_THREAD_PROVIDES_FUTURE_CONTINUATION", { public = true })
    add_defines("BOOST_THREAD_PROVIDES_EXECUTORS", { public = true })
    add_defines("BOOST_THREAD_USES_MOVE", { public = true })
    add_packages("boost", { public = true })
    add_packages("fmt")
    add_packages("spdlog")
    add_packages("range-v3")
    add_packages("scope_guard")

includes("test/")
